### ISSUE TITLE
[New Request] Variable in auth file...

### ISSUE THREAD

**Issue by serge-fabiano** [VinceZK/authorization#1]
Hi,

Is it possible to have values replaced at runtime?

For instance: the user can only update his own profile

Then I would expect his ID to be part of the authorization value.

Let me know.

Thanks,
Serge.

**Comment by serge-fabiano** [comment]
I used Mustache to templatise the authorisation file and put dynamic content.

**Comment by VinceZK** [comment]
Yes, it is possible. 

The raw profiles will be re-compiled by each login session. Once the user re-login, the new auth values take effect.
