### ISSUE TITLE
[Question] Compiled Auth in JWT token

### ISSUE THREAD

**Issue by serge-fabiano** [VinceZK/authorization#2]
I use JWT token to ensure stateless authentication.

Does the compiled profile can be set in the token and pass over the network in each HTTP request in term of weight?

Thanks,
Serge.

**Comment by serge-fabiano** [comment]
I just did it and the payload is acceptable.
Just wonder why that the compiled string is equals to the non compiled one...

**Comment by VinceZK** [comment]
The compiled profile won't pass over the network in each HTTP request. 

The compiled profile merge all the raw profiles and compress them into a checkable format. In real use cases, one can be assigned with multiple raw profiles, and they must have overlaps. By compiling raw profiles, we can save session storage and improve check performance.
