### ISSUE TITLE
[Request] Deny Permission

### ISSUE THREAD

**Issue by ghost** [VinceZK/authorization#3]
First, I really like this authorization model; simple yet flexible.  One thing that doesn't seem to be present is an ability to "deny" permission.  The "Exclude" setting of the "Option" field isn't the same, because it actually is designed to say, "Allow everything else".  If another authorization object "Includes" an authorization field value that was "excluded" by another authorization object, the permission will be granted.  A deny model would allow a developer\user to express that even if an authorization field value is "allowed" in other authorization objects, the denial of permission overrides the allow.

I poked around in the code a little bit to see how it might be implemented. The one thought I had that I felt was probably accurate, is that the expression of "Allow" vs "Deny" could probably be best expressed at the "Authorization Object" level.  The part I couldn't figure out was how to bring it all together in the "check" function without over-complicating it.

**Comment by VinceZK** [comment]
The easiest way I can imagine is you use a placeholder('!' for example) to represent "Deny". If any of the auth field of an auth object is assigned with value '!' (as opposite to '*'), then the whole auth object is denied. 

Sorry, I won't add this feature in my code line. As I think it will make the authorization trace complex. The right way to deny a permission should be removing the auth object or the values from profiles. So, I would add more authorization tracing ability.
