### ISSUE TITLE
[Bug] Possible undefined in check method of authorization object

### ISSUE THREAD

**Issue by sebastien-savalle** [VinceZK/authorization#5]
Hello,

First of all, I would like to thank you for developing this package which is very convenient. It's easy to define role based permission.

In my use case, I have two role: admin and basic.

The admin can do anything: manage user and message (CRUD operation).
The user can only read messages.

The authorization profile could be:

```
Admin
[
    {   "AuthObject": "user",
        "AuthFieldValue":{
            "Action": ["Create","Read","Update,"Delete"]
        }
    },
    {
        "AuthObject": "blog",
        "AuthFieldValue":{
            "Action": ["Create","Read","Update,"Delete"]
        }
    }
]
Basic
[
    {
        "AuthObject": "blog",
        "AuthFieldValue":{
            "Action": ["Read"]
        }
    }
]
```

With this example, when I want to check if a basic user can manage a user, an undefined will be thrown in the check method because no permission will be found (grantedPermission is undefined):

```
var grantedPermission =
        find(this.profile, function(authorization){
            return authorization.AuthObject === authObject;
        });

    return every(requiredPermission,function(value, field){
        let _grantedValue = grantedPermission.AuthFieldValue[field];
        if(_grantedValue){
```

It could be great to return before calling the every function.

Thanks

**Comment by VinceZK** [comment]
Thanks for the catching. 
The bug is fixed. But meanwhile, I found the code is quite old, ES5 still. Maybe it is time to improve it :-)

**Comment by sebastien-savalle** [comment]
Thanks for the quick fix. 
It allows to reduce authorization object.

It's quite old, but it's easy to use and it works pretty well.
